# Generated by Django 5.2.6 on 2025-09-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60)),
                ('celular', models.CharField(blank=True, max_length=15)),
                ('cursos', models.ManyToManyField(blank=True, related_name='professores', to='escola.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avaliacao', models.CharField(default='Prova', max_length=100)),
                ('data', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='escola.curso')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='escola.estudante')),
            ],
            options={
                'unique_together': {('estudante', 'curso', 'avaliacao', 'data')},
            },
        ),
    ]
